name: habitat2
channels:
  - pytorch
  - plotly
  - aihabitat
  - https://repo.continuum.io/pkgs/free
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.3.2=py36_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - brotlipy=0.7.0=py36h27cfd23_1003
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py36h5fab9bb_1
  - cffi=1.12.2=py36h2e261b9_1
  - cloudpickle=1.6.0=py_0
  - cmake=3.12.2=h52cb24c_0
  - cryptography=3.3.1=py36h3c74f83_1
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2.30.0=py_0
  - dataclasses=0.7=py36_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gitdb=4.0.5=py_0
  - gitpython=3.1.12=pyhd3eb1b0_1
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.13=h85f3911_1
  - headless=1.0=0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.2=py_0
  - importlib_metadata=1.5.0=py36_0
  - inflect=4.1.0=py36_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - isort=4.3.21=py36_0
  - jaraco.itertools=5.0.0=py_0
  - jedi=0.16.0=py36_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=habf39ab_1
  - jsonschema=3.2.0=py36_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.1=py36_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.4=h173b8e3_0
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.2=py36h7b6447c_0
  - lcms2=2.11=h396b838_0
  - libcurl=7.64.0=h20c2e04_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libllvm8=8.0.1=hc9558a2_0
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.1=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.31.0=py36hfa65bc7_1
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h250f245_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - more-itertools=8.2.0=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.6=he412f7d_0
  - networkx=2.5=py_0
  - ninja=1.8.2=py36h6bb024c_1
  - notebook=6.0.3=py36_0
  - numba=0.48.0=py36hb3f55d8_0
  - olefile=0.46=py36_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1j=h27cfd23_0
  - pandas=1.1.3=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.0=py_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=19.0.3=py36_0
  - plotly=4.14.3=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.5.2=py_0
  - pylint=2.4.3=py36_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.6=py_0
  - pyqt=4.11.4=py36_3
  - pyrsistent=0.15.7=py36h7b6447c_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.8=h0371630_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.7.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.5=pyhd3eb1b0_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.3.1=py36he6145b8_1
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=4.8.7=2
  - quaternion=2019.3.18.14.33.20=py36hc1659b7_0
  - readline=7.0=h7b6447c_5
  - requests=2.25.1=pyhd3eb1b0_0
  - retrying=1.3.3=py36_2
  - rhash=1.3.8=h1ba5d50_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py36_0
  - sip=4.18=py36_1
  - six=1.15.0=py36h06a4308_0
  - smmap=3.0.4=py_0
  - sqlite=3.27.2=h7b6447c_0
  - tbb=2019.4=hfd86e86_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.11.1=py_0
  - torchtext=0.8.1=py36
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.55.1=pyhd3eb1b0_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36h7b6447c_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_4
  - wrapt=1.11.2=py36h7b6447c_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxinerama=1.1.4=hf484d3e_1000
  - xorg-libxrandr=1.5.2=h516909a_1
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-randrproto=1.5.0=h516909a_1001
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.11.0
    - ase==3.20.1
    - astor==0.8.1
    - beautifulsoup4==4.7.1
    - beautifultable==0.7.0
    - boto3==1.16.59
    - botocore==1.19.59
    - cached-property==1.5.2
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==6.7
    - docker==3.6.0
    - docker-pycreds==0.4.0
    - evalai==1.3.12
    - fsspec==0.8.4
    - future==0.18.2
    - gast==0.2.2
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - grpcio==1.33.2
    - gym==0.10.9
    - h5py==3.1.0
    - habitat-sim==0.1.6
    - ifcfg==0.21
    - isodate==0.6.0
    - jmespath==0.10.0
    - joblib==0.17.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lxml==4.6.2
    - markdown==3.3.3
    - moviepy==2.0.0.dev2
    - numpy==1.19.1
    - oauthlib==3.1.0
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.11
    - pygraphviz==1.6
    - python-dateutil==2.7.3
    - python-louvain==0.14
    - pytorch-lightning==1.1.0
    - rdflib==5.0.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s3transfer==0.3.4
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - setuptools==50.3.2
    - soupsieve==2.1
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.8
    - torch-geometric==1.6.2
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - torchvision==0.7.0
    - urllib3==1.26.2
    - validators==0.12.6
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - yacs==0.1.8
prefix: /srv/flash1/jye72/anaconda3/envs/habitat2
